339268: stlink-1.6.1-alt2
- Revived the package (no code changes). It's useful, and it has been deleted
  due to a bogus compiler warning:
  error: 'stlink_open_usb' accessing 64 bytes in a region of size 28 [-Werror=stringop-overflow=]
  This warning is a false positive. GCC 11, 12 are known to produce a lot of
  false positives with `-Wstringop-overflow`. As a result Linux (the kernel)
  disables `-Wstringop-overflow` when compiling with GCC 11, see the commit
  a5e0ace04fbf56c17 `init: Kconfig: Disable -Wstringop-overflow for GCC-11`.
  With GCC 13 `-Wstringop-overflow` is much better, so the (same) code
  compiles (and runs) just fine.